### PR TITLE
 Merging all features into dev branch

### PR DESCRIPTION
**Pull request by vamsiboyella**
Please update comments whatever is required

### CODE REVIEW

**Comment by matheen5757** [comment]
Hard coding in Admin password, this is to be changed and some of the code is missing comments

**Review by sangmeshpatlolla — CHANGES_REQUESTED** [review]
unused variables are giving few warnings, redendent code. add more comments

**Review by matheen5757 — CHANGES_REQUESTED** [review]
Hard coding in Admin password, this is to be changed and some of the code is missing comments

**Review by iambaji — APPROVED** [review]
all good, approving merge

**Pull request merged**
