### PR TITLE
Merging into master

### PR DESCRIPTION
**Pull request by matheen5757**
Please check all the functionalities of the project.

### CODE REVIEW

**Review by vamsiboyella — CHANGES_REQUESTED** [review]
1. Please add bin and obj files in git ignore .(Baji)
2. Missing If and endif in header files, matheen pls add it and doxygen comments in the  validations.h and admin.h files
3.Sangamesh pls add config file.

4.
3,

**Comment by iambaji** [comment]
removed obj and bin folder from repo and fixed issue with gitignore

**Review by iambaji — APPROVED** [review]
fixed git ignore issue. all good.

**Review by sangmeshpatlolla — APPROVED** [review]
everything is good, any minor changes will be made in master branch

**Review by vamsiboyella — APPROVED** [review]
looks good , hoping changes will be there in master branch

**Comment by matheen5757** [comment]
comments for all the header files are updated

**Pull request merged**
